#!/bin/bash


EXPECTED_ARGS=1

if [ $# -ne $EXPECTED_ARGS ]
then
  echo "Usage: `basename $0` [project-name-without-space]"
  exit 1
fi

DIR=${1}

if [ -d "$DIR" ]; then
  echo "Warning: folder $DIR already exists.. stopping"
  exit 1
fi

# cp -r ~/config/templates/empty-java-code $DIR
git clone git@github.com:alexandrebouchard/java-gradle-template.git $1
cd $DIR
yes | rm -r .git
rm create-java-project
rm README.md

# substitute all instance of the string PROJECTNAME to the name of the project:

# in file name
find . | grep PROJECTNAME | while read FILE
do
    mv $FILE $(echo $FILE | sed "s/PROJECTNAME/$1/g") 2> /dev/null
done

# in their contents
find .  -type f | while read FILE
do
    cat $FILE | sed "s/PROJECTNAME/$1/g" > $FILE.temp 2> /dev/null
    mv $FILE.temp $FILE
done

# same for PROJECTDIR, in the contents only:
PROJECTPATH=`pwd`
find .  -type f | while read FILE
do
    cat $FILE | sed "s/PROJECTPATH/${PROJECTPATH}/g" > $FILE.temp 2> /dev/null
    mv $FILE.temp $FILE
done

gradle eclipse
cd ..
