#!/bin/bash


EXPECTED_ARGS=1

if [ $# -ne $EXPECTED_ARGS ]
then
  echo "Usage: `basename $0` [project-name-without-space]"
  exit 1
fi

DIR=${1}

if [ -d "$DIR" ]; then
  echo "Warning: folder $DIR already exists.. stopping"
  exit 1
fi

cp -r ~/config/templates/empty-java-code $DIR

cd $DIR
# substitute all instance of the string PROJECTNAME to the name of the project:

# in file name
find . | grep PROJECTNAME | while read FILE
do
    # modify line below to do what you need, then remove leading "echo" 
    mv $FILE $(echo $FILE | sed "s/PROJECTNAME/$1/g") 2> /dev/null
done

# in their contents
find .  -type f | while read FILE
do
    # modify line below to do what you need, then remove leading "echo" 
    cat $FILE | sed "s/PROJECTNAME/$1/g" > $FILE.temp 2> /dev/null
    mv $FILE.temp $FILE
done

gradle eclipse
cd ..
